### ISSUE TITLE
URL Validation for CustomRPC Form

### ISSUE THREAD

**Issue by chikeichan** [kyokan/bob-wallet#188]
- [x] CustomRPCModal should handle network type 
- [x] CustomRPCModal should validate that the endpoint has the right network type
- [x] CustomRPCModal should validate the url on frontend (parseable by the URL Class)
- [ ] Test Connection action should surface better error message for debugging (e.g. wrong network, api not found, etc)

-----------------
Fresh install, empty datadir, using `npm run dev`, loads OK.

 I love the new settings page layout, very clean and easy to navigate 👍 

But still having some issues.

Started fine, switched to regtest. Went to settings and clicked 'stop' -- bob logged me out and returned to "enter your seed phrase" screen again. I did so, and then I got stuck on "syncing wallet 0%" -- I didn't have a chance to enter the IP of my remote hsd node yet.

So quit and relaunched. This time I was able to go to settings and enter remote hsd info. I tried setting remote node url to a raspberry pi running hsd on my LAN by its IP address. I think there should be a timeout here because it just tried connecting forever and I must've entered somthing wrong. Couldn't cancel and try again.  I noticed this error in the log: ` Invalid URL: 10.0.1.5`

Quit and relaunch. This time stuck on "loading node...". Brick wall, every restart.

Cleaned out datadir and start over, try again. This time I set the remote node URL specifically to `http://10.0.1.5:12037` (because I also noticed in the log it was trying to hit port `80`, not the default rpc port, so without specifying port it didn't connect)

Now we're in business! I watched the remote hsd log, Bob seemed to rescanning OK - although I wasnt seeing the "syncing %" modal from https://github.com/kyokan/bob-wallet/pull/117  While rescanning, the Bob UI doesn't really work, it won't load auction details etc until the rescan job is done.

Before rescan was done though I tried something else, switching to another node. This time, local regtest. So set the URL to `http://127.0.0.1:14037` Bob didn't complain but it should have - Bob was configured for mainnet but that node is on regtest. I noticed the "network" setting is disabled when you configure a remote hsd -- I don't think it should be -- a mainnet wallet trying to rescan from a regtest node will be weirdo, and there should maybe be a check in place for that.

I'm happy to help with code review but the PR is really big (`+13,009 −160` !) It might be easier to get review if it were split up into a few smaller patches. Like
1- refactor settings page
2- use walletnode internally
3- option to switch to remote node
Just my two cents. Especially up to just try out (2) with everything from rescans to seed imports to auctions and make sure nothing has changed in Bob before adding the real feature.

_Originally posted by @pinheadmz in https://github.com/kyokan/bob-wallet/pull/171#issuecomment-667300710_

**Comment by pinheadmz** [comment]
bump! This is still an issue. For example I launched bob in dev mode on regtest, opened the custom rpc settings and just clicked "confirm" without changing anything (including network:main and all the empty fields). Bob then enters an unrecoverable state:

<img width="209" alt="Screen Shot 2021-06-30 at 10 56 47 AM" src="https://user-images.githubusercontent.com/2084648/123983644-09ee5900-d992-11eb-92a6-bd5d7b658715.png">


```
Sending IPC method error. { jsonrpc: '2.0', method: 'Node.reset', params: [], id: 171 } Error: Malformed URL.
    at ClientOptions.fromOptions (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bcurl/lib/client.js:460:15)
    at new ClientOptions (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bcurl/lib/client.js:383:12)
    at new Client (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bcurl/lib/client.js:30:17)
    at new NodeClient (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/hs-client/lib/node.js:24:5)
    at NodeService.setCustomRPCClient (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/node/service.js:194:19)
    at NodeService.start (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/node/service.js:86:9)
    at NodeService.reset (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/node/service.js:214:5)
Stack: Error: Malformed URL.
    at ClientOptions.fromOptions (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bcurl/lib/client.js:460:15)
    at new ClientOptions (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bcurl/lib/client.js:383:12)
    at new Client (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bcurl/lib/client.js:30:17)
    at new NodeClient (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/hs-client/lib/node.js:24:5)
    at NodeService.setCustomRPCClient (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/node/service.js:194:19)
    at NodeService.start (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/node/service.js:86:9)
    at NodeService.reset (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/node/service.js:214:5)
walletdb error Error: Timed out waiting for connection. Reconnecting...
    at Socket.error (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/lib/socket.js:327:24)
    at Socket.stall (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/lib/socket.js:393:14)
    at Timeout._onTimeout (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/lib/socket.js:370:41)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
walletdb error Error: Network error: ws://127.0.0.1:12037/socket.io/?transport=websocket: connect ECONNREFUSED 127.0.0.1:12037
    at Socket.onError (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/lib/socket.js:245:24)
    at Client.ws.onerror (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/lib/socket.js:174:18)
    at Client.dispatchEvent (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/vendor/faye-websocket.js:3179:30)
    at Client._emitError (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/vendor/faye-websocket.js:3117:10)
    at Socket.<anonymous> (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/bsock/vendor/faye-websocket.js:3086:12)
    at Socket.emit (events.js:228:7)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

...and there is no way to recover. Even restarting looks pretty bad (where is the wallet I already created?!)

<img width="728" alt="Screen Shot 2021-06-30 at 10 58 33 AM" src="https://user-images.githubusercontent.com/2084648/123983797-238fa080-d992-11eb-8a02-8dc1d8c511e4.png">


So I think we need two things:

- Do not allow "confirm" custom RPC settings without testing connection
and / or
- If custom RPC fails or if node connection fails in any way, force user to the settings screen (maybe?) to fix it.
