### ISSUE TITLE
Consider bumping electron to version 11

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#389]
Currently we require version 9:

https://github.com/kyokan/bob-wallet/blob/master/package.json#L118

However there is a super weird bug in Electron in how `assert()` is handled, and I was getting this error testing out shakedex stuff:

```
TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:270:25)
    at innerOk (assert.js:361:17)
    at strict (assert.js:843:3)
    at exports.fillSwap (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/shakedex/src/swapService.js:195:3)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at fulfillSwap (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/shakedex/service.js:117:23)
Stack: TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:270:25)
    at innerOk (assert.js:361:17)
    at strict (assert.js:843:3)
    at exports.fillSwap (/Users/matthewzipkin/Desktop/work/bob-wallet/node_modules/shakedex/src/swapService.js:195:3)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at fulfillSwap (/Users/matthewzipkin/Desktop/work/bob-wallet/app/background/shakedex/service.js:117:23)
```

Issue: https://github.com/electron/electron/issues/24577
Fix: https://github.com/electron/electron/pull/24579

So this fix was merged into Electron starting in version 11.: https://github.com/electron/electron/releases/tag/v11.0.0-beta.1

**Comment by rithvikvibhu** [comment]
#444
