### ISSUE TITLE
There isnt possible to open info about HNS domain humanto in reveal BID period

### ISSUE THREAD

**Issue by humantoai** [kyokan/bob-wallet#652]
## Expected Behavior
Detail of auction

## Current Behavior
There isnt possible to open info about HNS domain humanto in reveal BID period.
Application say:
Something went wrong fetching this name. Please try again.
Oops! Would you mind telling us what went wrong?

## Steps to Reproduce
Click on detail of humanto auction from homepage

## Logs
[D:2024-01-05T14:59:33Z] (wallet) Adding block: 206165.
[W:2024-01-05T14:59:33Z] (chain) Unknown version bits in block 206166: 00000002.
[D:2024-01-05T14:59:33Z] (chain) Retargetting to: 0000000000000007a3d600000000000000000000000000000000000000000000 (0x1907a3d6).
[D:2024-01-05T14:59:33Z] (wallet) Adding block: 206166.
[D:2024-01-05T14:59:33Z] (chain) Retargetting to: 0000000000000007d7fd00000000000000000000000000000000000000000000 (0x1907d7fd).
[D:2024-01-05T14:59:33Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T14:59:33Z] (wallet) Adding block: 206167.
[D:2024-01-05T14:59:33Z] (net) Resolved height for 1 peers.
[I:2024-01-05T14:59:33Z] (net) Received 147 addrs (hosts=395, peers=4) (194.50.5.28:12038).
[I:2024-01-05T14:59:33Z] (peer) Peer initialized compact blocks (mode=0, version=1) (194.50.5.28:12038).
[D:2024-01-05T14:59:33Z] (net) Received 73 block hashes from peer (194.50.5.28:12038).
[D:2024-01-05T14:59:33Z] (net) Received existing hash (194.50.5.28:12038).
[D:2024-01-05T14:59:33Z] (peer) Requesting inv packet from peer with getblocks (194.50.5.28:12038).
[D:2024-01-05T14:59:33Z] (peer) Sending getblocks (hash=000000000000000510c586356a1b8fb5753d5ace20c00be916c4c7ab04c0072c, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T14:59:34Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T14:59:37Z] (net) Error: Connection timed out. (105.186.133.71:39001)
[D:2024-01-05T14:59:38Z] (net) Connecting to 104.254.246.153:12038.
[I:2024-01-05T14:59:38Z] (net) Connected to 104.254.246.153:12038.
[D:2024-01-05T14:59:39Z] (peer) Received verack (104.254.246.153:12038).
[I:2024-01-05T14:59:39Z] (net) Received version (104.254.246.153:12038): version=3 height=206167 services=11 agent=/hsd:4.99.0/
[D:2024-01-05T14:59:39Z] (node) Added time data: samples=4, offset=-1 (0 minutes).
[D:2024-01-05T14:59:39Z] (peer) Version handshake complete (104.254.246.153:12038).
[D:2024-01-05T14:59:39Z] (peer) Requesting inv packet from peer with getblocks (104.254.246.153:12038).
[D:2024-01-05T14:59:39Z] (peer) Sending getblocks (hash=000000000000000510c586356a1b8fb5753d5ace20c00be916c4c7ab04c0072c, stop=0000000000000000000000000000000000000000000000000000000000000000).
[I:2024-01-05T14:59:39Z] (net) Received 106 addrs (hosts=395, peers=4) (104.254.246.153:12038).
[I:2024-01-05T14:59:39Z] (peer) Peer initialized compact blocks (mode=0, version=1) (104.254.246.153:12038).
[D:2024-01-05T14:59:42Z] (wallet-http) Request for method=POST path=/wallet/mywallet/unlock (127.0.0.1).
[E:2024-01-05T14:59:42Z] (node) Could not decrypt.
    at Object.decipher (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bcrypto\lib\native\aes.js:50:36)
    at MasterKey._unlock (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\hsd\lib\wallet\masterkey.js:171:22)
    at async MasterKey.unlock (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\hsd\lib\wallet\masterkey.js:142:14)
    at async Route.handler (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\hsd\lib\wallet\http.js:386:7)
    at async Router.handle (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\router.js:100:9)
    at async HTTP._handleStack (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\server.js:294:9)
    at async HTTP._handleRequest (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\server.js:203:9)
    at async Server.<anonymous> (C:\Users\jindr\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\server.js:126:9)
[D:2024-01-05T14:59:48Z] (wallet-http) Request for method=POST path=/wallet/mywallet/unlock (127.0.0.1).
[D:2024-01-05T14:59:48Z] (wallet-http) Request for method=GET path=/wallet/mywallet (127.0.0.1).
[D:2024-01-05T14:59:48Z] (wallet-http) Request for method=GET path=/wallet/mywallet (127.0.0.1).
[D:2024-01-05T14:59:48Z] (wallet-http) Request for method=GET path=/wallet/mywallet/master (127.0.0.1).
[D:2024-01-05T14:59:48Z] (wallet-http) Request for method=POST path=/wallet/mywallet/lock (127.0.0.1).
[D:2024-01-05T14:59:48Z] (node-rpc) Handling RPC call: getblockchaininfo.
[D:2024-01-05T14:59:48Z] (node-rpc) []
[D:2024-01-05T14:59:48Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:01:32Z] (hostlist) Writing hosts to C:\Users\jindr\AppData\Roaming\Bob\hsd_data\hosts.json.
[D:2024-01-05T15:02:23Z] (net) Received 1 block hashes from peer (2.59.135.213:12038).
[D:2024-01-05T15:02:23Z] (net) Requesting 1/1 blocks from peer with getdata (2.59.135.213:12038).
[D:2024-01-05T15:02:23Z] (chain) Retargetting to: 0000000000000007e87700000000000000000000000000000000000000000000 (0x1907e877).
[D:2024-01-05T15:02:23Z] (wallet) Adding block: 206168.
[D:2024-01-05T15:02:23Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:02:23Z] (net) Received 1 block hashes from peer (104.254.246.153:12038).
[D:2024-01-05T15:02:23Z] (net) Received existing hash (104.254.246.153:12038).
[D:2024-01-05T15:02:23Z] (peer) Requesting inv packet from peer with getblocks (104.254.246.153:12038).
[D:2024-01-05T15:02:23Z] (peer) Sending getblocks (hash=00000000000000040b5c21a260577fca021be629bfa2226258de16c34942d3ae, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:02:24Z] (net) Received 1 block hashes from peer (91.218.58.24:12038).
[D:2024-01-05T15:02:24Z] (net) Received existing hash (91.218.58.24:12038).
[D:2024-01-05T15:02:24Z] (peer) Requesting inv packet from peer with getblocks (91.218.58.24:12038).
[D:2024-01-05T15:02:24Z] (peer) Sending getblocks (hash=00000000000000040b5c21a260577fca021be629bfa2226258de16c34942d3ae, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:02:24Z] (net) Received 1 block hashes from peer (194.50.5.28:12038).
[D:2024-01-05T15:02:24Z] (net) Received existing hash (194.50.5.28:12038).
[D:2024-01-05T15:02:24Z] (peer) Requesting inv packet from peer with getblocks (194.50.5.28:12038).
[D:2024-01-05T15:02:24Z] (peer) Sending getblocks (hash=00000000000000040b5c21a260577fca021be629bfa2226258de16c34942d3ae, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:03:16Z] (net) Received 1 block hashes from peer (2.59.135.213:12038).
[D:2024-01-05T15:03:16Z] (net) Requesting 1/1 blocks from peer with getdata (2.59.135.213:12038).
[D:2024-01-05T15:03:16Z] (chain) Retargetting to: 0000000000000007e07b00000000000000000000000000000000000000000000 (0x1907e07b).
[D:2024-01-05T15:03:16Z] (wallet) Adding block: 206169.
[D:2024-01-05T15:03:16Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:03:16Z] (net) Received 1 block hashes from peer (194.50.5.28:12038).
[D:2024-01-05T15:03:16Z] (net) Received existing hash (194.50.5.28:12038).
[D:2024-01-05T15:03:16Z] (peer) Requesting inv packet from peer with getblocks (194.50.5.28:12038).
[D:2024-01-05T15:03:16Z] (peer) Sending getblocks (hash=0000000000000001345bd6609868457f9f80e14be420ceb2f07920efe2aaca06, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:03:16Z] (net) Received 1 block hashes from peer (91.218.58.24:12038).
[D:2024-01-05T15:03:16Z] (net) Received existing hash (91.218.58.24:12038).
[D:2024-01-05T15:03:16Z] (peer) Requesting inv packet from peer with getblocks (91.218.58.24:12038).
[D:2024-01-05T15:03:16Z] (peer) Sending getblocks (hash=0000000000000001345bd6609868457f9f80e14be420ceb2f07920efe2aaca06, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:03:17Z] (net) Received 1 block hashes from peer (104.254.246.153:12038).
[D:2024-01-05T15:03:17Z] (net) Received existing hash (104.254.246.153:12038).
[D:2024-01-05T15:03:17Z] (peer) Requesting inv packet from peer with getblocks (104.254.246.153:12038).
[D:2024-01-05T15:03:17Z] (peer) Sending getblocks (hash=0000000000000001345bd6609868457f9f80e14be420ceb2f07920efe2aaca06, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:03:55Z] (net) Received 1 block hashes from peer (2.59.135.213:12038).
[D:2024-01-05T15:03:55Z] (net) Requesting 1/1 blocks from peer with getdata (2.59.135.213:12038).
[W:2024-01-05T15:03:55Z] (chain) Unknown version bits in block 206170: 00000002.
[D:2024-01-05T15:03:55Z] (chain) Retargetting to: 0000000000000007fad800000000000000000000000000000000000000000000 (0x1907fad8).
[D:2024-01-05T15:03:55Z] (wallet) Adding block: 206170.
[D:2024-01-05T15:03:55Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:03:56Z] (net) Received 1 block hashes from peer (104.254.246.153:12038).
[D:2024-01-05T15:03:56Z] (net) Received existing hash (104.254.246.153:12038).
[D:2024-01-05T15:03:56Z] (peer) Requesting inv packet from peer with getblocks (104.254.246.153:12038).
[D:2024-01-05T15:03:56Z] (peer) Sending getblocks (hash=00000000000000072cbf7b94a3fade175c4139b3e5ef846b163cfd930e4e873c, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:03:56Z] (net) Received 1 block hashes from peer (194.50.5.28:12038).
[D:2024-01-05T15:03:56Z] (net) Received existing hash (194.50.5.28:12038).
[D:2024-01-05T15:03:56Z] (peer) Requesting inv packet from peer with getblocks (194.50.5.28:12038).
[D:2024-01-05T15:03:56Z] (peer) Sending getblocks (hash=00000000000000072cbf7b94a3fade175c4139b3e5ef846b163cfd930e4e873c, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:04:12Z] (net) Received 1 block hashes from peer (91.218.58.24:12038).
[D:2024-01-05T15:04:12Z] (net) Received existing hash (91.218.58.24:12038).
[D:2024-01-05T15:04:12Z] (peer) Requesting inv packet from peer with getblocks (91.218.58.24:12038).
[D:2024-01-05T15:04:12Z] (peer) Sending getblocks (hash=00000000000000072cbf7b94a3fade175c4139b3e5ef846b163cfd930e4e873c, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:06:01Z] (net) Received 1 block hashes from peer (2.59.135.213:12038).
[D:2024-01-05T15:06:01Z] (net) Requesting 1/1 blocks from peer with getdata (2.59.135.213:12038).
[D:2024-01-05T15:06:01Z] (net) Received 1 block hashes from peer (104.254.246.153:12038).
[W:2024-01-05T15:06:01Z] (chain) Unknown version bits in block 206171: 00000002.
[D:2024-01-05T15:06:01Z] (chain) Retargetting to: 0000000000000007f56400000000000000000000000000000000000000000000 (0x1907f564).
[D:2024-01-05T15:06:01Z] (wallet) Adding block: 206171.
[D:2024-01-05T15:06:01Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:06:01Z] (net) Resolved height for 1 peers.
[D:2024-01-05T15:06:01Z] (net) Received 1 block hashes from peer (91.218.58.24:12038).
[D:2024-01-05T15:06:01Z] (net) Received existing hash (91.218.58.24:12038).
[D:2024-01-05T15:06:01Z] (peer) Requesting inv packet from peer with getblocks (91.218.58.24:12038).
[D:2024-01-05T15:06:01Z] (peer) Sending getblocks (hash=00000000000000070cd7f849362e6dca4c69efb2d210156ee67e3ae758d78397, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:06:01Z] (net) Received 1 block hashes from peer (194.50.5.28:12038).
[D:2024-01-05T15:06:01Z] (net) Received existing hash (194.50.5.28:12038).
[D:2024-01-05T15:06:01Z] (peer) Requesting inv packet from peer with getblocks (194.50.5.28:12038).
[D:2024-01-05T15:06:01Z] (peer) Sending getblocks (hash=00000000000000070cd7f849362e6dca4c69efb2d210156ee67e3ae758d78397, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:08:49Z] (node-rpc) Handling RPC call: getblockchaininfo.
[D:2024-01-05T15:08:49Z] (node-rpc) []
[D:2024-01-05T15:08:49Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:09:27Z] (node-rpc) Handling RPC call: getblockchaininfo.
[D:2024-01-05T15:09:27Z] (node-rpc) []
[D:2024-01-05T15:09:27Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:10:54Z] (node-rpc) Handling RPC call: getblockchaininfo.
[D:2024-01-05T15:10:54Z] (node-rpc) []
[D:2024-01-05T15:10:54Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:11:04Z] (node-rpc) Handling RPC call: getblockchaininfo.
[D:2024-01-05T15:11:04Z] (node-rpc) []
[D:2024-01-05T15:11:04Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:11:32Z] (node-rpc) Handling RPC call: getblockchaininfo.
[D:2024-01-05T15:11:32Z] (node-rpc) []
[D:2024-01-05T15:11:32Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:12:10Z] (net) Received 1 block hashes from peer (2.59.135.213:12038).
[D:2024-01-05T15:12:10Z] (net) Requesting 1/1 blocks from peer with getdata (2.59.135.213:12038).
[D:2024-01-05T15:12:10Z] (chain) Retargetting to: 0000000000000007e68d00000000000000000000000000000000000000000000 (0x1907e68d).
[D:2024-01-05T15:12:10Z] (wallet) Adding block: 206172.
[D:2024-01-05T15:12:10Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2024-01-05T15:12:10Z] (net) Received 1 block hashes from peer (104.254.246.153:12038).
[D:2024-01-05T15:12:10Z] (net) Received existing hash (104.254.246.153:12038).
[D:2024-01-05T15:12:10Z] (peer) Requesting inv packet from peer with getblocks (104.254.246.153:12038).
[D:2024-01-05T15:12:10Z] (peer) Sending getblocks (hash=0000000000000006babe6dbc96f28bf223827e401050cc38177ed2a32666943c, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:12:10Z] (net) Received 1 block hashes from peer (194.50.5.28:12038).
[D:2024-01-05T15:12:10Z] (net) Received existing hash (194.50.5.28:12038).
[D:2024-01-05T15:12:10Z] (peer) Requesting inv packet from peer with getblocks (194.50.5.28:12038).
[D:2024-01-05T15:12:10Z] (peer) Sending getblocks (hash=0000000000000006babe6dbc96f28bf223827e401050cc38177ed2a32666943c, stop=0000000000000000000000000000000000000000000000000000000000000000).
[D:2024-01-05T15:12:10Z] (net) Received 1 block hashes from peer (91.218.58.24:12038).
[D:2024-01-05T15:12:10Z] (net) Received existing hash (91.218.58.24:12038).
[D:2024-01-05T15:12:10Z] (peer) Requesting inv packet from peer with getblocks (91.218.58.24:12038).
[D:2024-01-05T15:12:10Z] (peer) Sending getblocks (hash=0000000000000006babe6dbc96f28bf223827e401050cc38177ed2a32666943c, stop=0000000000000000000000000000000000000000000000000000000000000000).

## Screencap
<img width="743" alt="image" src="https://github.com/kyokan/bob-wallet/assets/155752198/9f1802d2-e179-4e4a-a0e5-08278ffab975">

**Comment by rithvikvibhu** [comment]
Hey @humantoai!

If this was with SPV enabled, it should be fixed now. Do the names load fine now?
